#### This is a notebook demonstrating how to generate a FCIDUMP file from PySCF.
#### I am closely following the guidance provided in https://pyscf.org/user/gto.html

In [1]:
from pyscf import gto

In [2]:
## Building a molecule
## -------------------

#### Molecules can be built in many ways in PySCF. I am only following
#### the one that I like the most as of now.
mol = gto.Mole()
mol.atom = '''
    O  0  0  0
    H  0  1  0
    H  0  0  1'''
mol.unit = 'B'
mol.basis = {'O': 'cc-pvdz', 'H': 'cc-pvdz'}

If we need to distinguish the second H atom or want to use a different
basis set for it, we can use the following instead 
mol.basis = {'O': 'cc-pvdz', 'H': 'cc-pvdz', 'H@2': 'cc-pvdz'}


Can also provide the input in XYZ format: mol.atom = "sample.xyz"


We can also manually specify the basis set in the following way:



mol.basis = {'O': gto.basis.parse('''


C      S

       aaaaaaaa      aaaaaaaa

       aaaaaaaa      aaaaaaaa
       .
       .
       .

C      SP

       aaaaaaaa      aaaaaaaaa

       aaaaaaaa      aaaaaaaaa
       .
       .
       .

''')}

The function *gto.basis.parse()* can parse a basis string in *NWChem* format.

In [7]:
## Adding Symmetry
mol.symmetry = True
mol.symmetry_subgroup = "C2"
#mol.build()
#print(mol.topgroup)
#print(mol.groupname)

In [ ]:
## Specify the spin and charge

mol.spin = 0 # Number of unpaired electrons
mol.charge = 0

In [8]:
# Level of output
mol.verbose = 4

# If output is wanted in a file
#mol.output = 'Path to output.log'

# managing memory used
mol.max_memory = 1000 # MB

The max memory used by PySCF can also be altered by using PYSF_MAX_MEMORY variable.

To run PySCF as a python script specifying output.log and max memory:

* $python input.in -o path_to_output.log -m 1000 *

In [9]:
# Finally to build the molecule

mol.build()

Accessing the AO integrals generated by PySCF libcint library

In [10]:
kin = mol.intor('int1e_kin')
vnuc = mol.intor('int1e_nuc')
overlap = mol.intor('int1e_ovlp')
eri = mol.intor('int2e')

#### Now we know how to specify the molecule we need. So we will proceed to learn how to perform a Hartree-Fock Calculation in PySCF 

In [11]:
from pyscf import scf

In [12]:
mf = scf.RHF(mol)
mf.kernel()



******** <class 'pyscf.scf.hf_symm.SymAdaptedRHF'> ********
method = SymAdaptedRHF-RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-09
SCF conv_tol_grad = None
SCF max_cycles = 50
direct_scf = True
direct_scf_tol = 1e-13
chkfile to save SCF result = /var/folders/79/_jmtw35d26b_3pp5jf6l2ypm0000gn/T/tmppjt31nir
max_memory 1000 MB (current use 0 MB)
Freeze 0 electrons in irreps []
    10 free electrons in irreps A B
Set gradient conv threshold to 3.16228e-05
init E= -76.128303355102
HOMO (B) = -0.724924240226296  LUMO (A) = 0.146500178367236
cycle= 1 E= -74.7146531649627  delta_E= 1.41  |g|= 0.62  |ddm|= 1.99
HOMO (B) = -0.472042896066504  LUMO (A) = 0.230293076685481
cycle= 2 E= -74.7660607284013  delta_E= -0.0514  |g|= 0.235  |ddm|= 0.579
HOMO (B) = -0.561702690907202  LUMO (A) = 0.22377695902233
cycle= 3 E= -74.7735640050047  delta_E= -0.0075  |g|= 0.0256  |ddm|= 0.132
HOMO 

-74.77377389776407

In [17]:
mf.verbose=3
mf.analyze()

Wave-function symmetry = A
occupancy for each irrep:      A    B
                               3    2
**** MO energy ****
MO #1 (A #1), energy= -20.5070084858351 occ= 2
MO #2 (A #2), energy= -1.73080564983769 occ= 2
MO #3 (B #1), energy= -0.936404890607979 occ= 2
MO #4 (A #3), energy= -0.680987097119958 occ= 2
MO #5 (B #2), energy= -0.558416875072044 occ= 2
MO #6 (A #4), energy= 0.223422472230708 occ= 0
MO #7 (B #3), energy= 0.284514274178619 occ= 0
MO #8 (A #5), energy= 0.974164784853037 occ= 0
MO #9 (B #4), energy= 1.03121817935407 occ= 0
MO #10 (B #5), energy= 1.04812922419724 occ= 0
MO #11 (B #6), energy= 1.4326930906302 occ= 0
MO #12 (A #6), energy= 1.49171607004192 occ= 0
MO #13 (A #7), energy= 1.62813095792543 occ= 0
MO #14 (A #8), energy= 1.72759774104815 occ= 0
MO #15 (A #9), energy= 1.98233929485435 occ= 0
MO #16 (B #7), energy= 1.99005953758916 occ= 0
MO #17 (B #8), energy= 2.69497094340738 occ= 0
MO #18 (B #9), energy= 3.41916359337807 occ= 0
MO #19 (A #10), energy= 3.6227

((array([1.99997143e+00, 1.37372462e+00, 1.26656207e-02, 1.99069635e+00,
         1.72435980e+00, 1.72435980e+00, 2.72452689e-05, 3.99303962e-02,
         3.99303962e-02, 2.44785891e-03, 3.92313959e-03, 2.19450782e-02,
         2.44785891e-03, 1.98220846e-02, 4.98248736e-01, 1.99167769e-02,
         2.19034591e-03, 2.42964120e-04, 1.27533823e-03, 4.98248736e-01,
         1.99167769e-02, 2.19034591e-03, 1.27533823e-03, 2.42964120e-04]),
  array([-0.95625168,  0.47812584,  0.47812584])),
 array([7.13446152e-17, 1.26823413e+00, 1.26823413e+00]))

#### Summary

In [26]:
import pyscf
from pyscf import gto, scf

mol = gto.Mole()
mol.atom = '''
    O  0  0  0
    H  0  1  0
    H  0  0  1'''
mol.unit = 'B'
mol.basis = {'O': 'cc-pvdz', 'H': 'cc-pvdz'}
mol.symmetry = True
#mol.symmetry_subgroup = "C2"
mol.spin=0
mol.charge=0
mol.max_memory = 1000
mol.verbose=4
mol.build()

mf = scf.ROHF(mol)
mf.diis_space = 5
mf.kernel()

System: uname_result(system='Darwin', node='Arnabs-MacBook-Pro.local', release='21.2.0', version='Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64', machine='x86_64', processor='i386')  Threads 1
Python 3.8.8 (default, Apr 13 2021, 12:59:45) 
[Clang 10.0.0 ]
numpy 1.20.1  scipy 1.6.2
Date: Fri Feb 11 20:38:44 2022
PySCF version 2.0.1
PySCF path  /opt/anaconda3/lib/python3.8/site-packages/pyscf

[CONFIG] conf_file None
[INPUT] verbose = 4
[INPUT] num. atoms = 3
[INPUT] num. electrons = 10
[INPUT] charge = 0
[INPUT] spin (= nelec alpha-beta = 2S) = 0
[INPUT] symmetry True subgroup None
[INPUT] Mole.unit = B
[INPUT]  1 O      0.000000000000   0.000000000000   0.000000000000 AA    0.000000000000   0.000000000000   0.000000000000 Bohr
[INPUT]  2 H      0.000000000000   0.529177210920   0.000000000000 AA    0.000000000000   1.000000000000   0.000000000000 Bohr
[INPUT]  3 H      0.000000000000   0.000000000000   0.529177210920 AA    0.00000000000

-74.77377389776396

In [27]:
mf.analyze()

**** SCF Summaries ****
Total Energy =                         -74.773773897763959
Nuclear Repulsion Energy =              16.707106781186546
One-electron Energy =                 -134.134514758193490
Two-electron Energy =                   42.653634079242970
Wave-function symmetry = A1
occupancy for each irrep:     A1   A2   B1   B2
double occ                     3    0    1    1
single occ                     0    0    0    0
**** MO energy ****
                          Roothaan           | alpha              | beta
MO #1   (A1  #1 ) energy= -20.5070082222686  | -20.5070082222686  | -20.5070082222686  occ= 2
MO #2   (A1  #2 ) energy= -1.73080558965712  | -1.73080558965712  | -1.73080558965712  occ= 2
MO #3   (B1  #1 ) energy= -0.936404865914407 | -0.936404865914407 | -0.936404865914407 occ= 2
MO #4   (A1  #3 ) energy= -0.68098696733729  | -0.680986967337291 | -0.680986967337291 occ= 2
MO #5   (B2  #1 ) energy= -0.558416789342555 | -0.558416789342555 | -0.558416789342555 occ= 2
MO #6

((array([1.99997143e+00, 1.37372460e+00, 1.26656224e-02, 1.99069635e+00,
         1.72435978e+00, 1.72435978e+00, 2.72457606e-05, 3.99304057e-02,
         3.99304057e-02, 2.44785843e-03, 3.92313741e-03, 2.19450855e-02,
         2.44785843e-03, 1.98220874e-02, 4.98248741e-01, 1.99167849e-02,
         2.19034591e-03, 2.42964102e-04, 1.27533764e-03, 4.98248741e-01,
         1.99167849e-02, 2.19034591e-03, 1.27533764e-03, 2.42964102e-04]),
  array([-0.95625165,  0.47812583,  0.47812583])),
 array([7.13446251e-17, 1.26823419e+00, 1.26823419e+00]))

### Property calculations

In [28]:
mf.dip_moment()

Dipole moment(X, Y, Z, Debye):  0.00000,  1.26823,  1.26823


array([7.13446251e-17, 1.26823419e+00, 1.26823419e+00])

In [29]:
mf.mulliken_pop()

 ** Mulliken pop  **
pop of  0 O 1s        2.01109
pop of  0 O 2s        0.78505
pop of  0 O 3s        0.30264
pop of  0 O 2px       1.16798
pop of  0 O 2py       1.13845
pop of  0 O 2pz       1.13845
pop of  0 O 3px       0.72713
pop of  0 O 3py       0.24580
pop of  0 O 3pz       0.24580
pop of  0 O 3dxy      0.00219
pop of  0 O 3dyz      0.00419
pop of  0 O 3dz^2     0.02092
pop of  0 O 3dxz      0.00219
pop of  0 O 3dx2-y2    0.01194
pop of  1 H 1s        0.99241
pop of  1 H 2s        0.04896
pop of  1 H 2px       0.05025
pop of  1 H 2py       0.00663
pop of  1 H 2pz      -0.00017
pop of  2 H 1s        0.99241
pop of  2 H 2s        0.04896
pop of  2 H 2px       0.05025
pop of  2 H 2py      -0.00017
pop of  2 H 2pz       0.00663
 ** Mulliken atomic charges  **
charge of  0O =      0.19617
charge of  1H =     -0.09808
charge of  2H =     -0.09808


(array([ 2.01108760e+00,  7.85053721e-01,  3.02637785e-01,  1.16797914e+00,
         1.13845232e+00,  1.13845232e+00,  7.27126703e-01,  2.45804812e-01,
         2.45804812e-01,  2.19387428e-03,  4.19060666e-03,  2.09162409e-02,
         2.19387428e-03,  1.19390760e-02,  9.92413630e-01,  4.89628080e-02,
         5.02532033e-02,  6.62564180e-03, -1.71728017e-04,  9.92413630e-01,
         4.89628080e-02,  5.02532033e-02, -1.71728017e-04,  6.62564180e-03]),
 array([ 0.19616711, -0.09808356, -0.09808356]))

In [30]:
g = mf.Gradients()
g.kernel()



******** <class 'pyscf.grad.rohf.Gradients'> for <class 'pyscf.scf.hf_symm.SymAdaptedROHF'> ********
unit = Eh/Bohr
max_memory 1000 MB (current use 0 MB)
--------------- SymAdaptedROHF gradients ---------------
         x                y                z
0 O     0.0000000000     2.5563038548     2.5563038548
1 H    -0.0000000000    -2.6926893717     0.1363855169
2 H     0.0000000000     0.1363855169    -2.6926893717
----------------------------------------------


array([[ 1.56528467e-16,  2.55630385e+00,  2.55630385e+00],
       [-4.09865124e-16, -2.69268937e+00,  1.36385517e-01],
       [ 2.53336658e-16,  1.36385517e-01, -2.69268937e+00]])

### Our next goal is to run a MP2 calculation

In [40]:
# After RHF/ROHF run MP2 can be run with just the default setup by the
# following command
from pyscf import mp

mf.verbose=5
pyscf.mp.MP2(mf).kernel()


WARN: RMP2 method does not support ROHF method. ROHF object is converted to UHF object and UMP2 method is called.

Converting <class 'pyscf.scf.hf_symm.SymAdaptedROHF'> to UHF

******** <class 'pyscf.mp.ump2.UMP2'> ********
nocc = (5, 5), nmo = (24, 24)
max_memory 1000 MB (current use 0 MB)
E(UMP2) = -74.9479442606014  E_corr = -0.174170362837478


(-0.17417036283747783,
 (array([[[[ 0.00000000e+00,  1.10043825e-18, -4.72644385e-19, ...,
            -3.38813179e-19, -1.58063717e-18,  1.02999206e-17],
           [-1.10043825e-18,  0.00000000e+00,  2.72892726e-18, ...,
             1.74132739e-18,  6.01732206e-18,  1.61179630e-17],
           [ 4.72644385e-19, -2.72892726e-18,  0.00000000e+00, ...,
            -1.08420217e-19,  3.96208086e-18,  8.78203760e-18],
           ...,
           [ 3.38813179e-19, -1.74132739e-18,  1.08420217e-19, ...,
             0.00000000e+00,  4.27101766e-18,  5.42101086e-20],
           [ 1.58063717e-18, -6.01732206e-18, -3.96208086e-18, ...,
            -4.27101766e-18,  0.00000000e+00,  3.48680759e-17],
           [-1.02999206e-17, -1.61179630e-17, -8.78203760e-18, ...,
            -5.42101086e-20, -3.48680759e-17,  0.00000000e+00]],
  
          [[ 0.00000000e+00,  2.71697009e-18,  1.26995053e-04, ...,
            -5.77795997e-05,  1.13702439e-18,  2.01819426e-04],
           [-2.71697009e-18,  0.0

In [38]:
# To run DIIS
# -----------
#mf.DIIS=scf.ADIIS
#mf.diis_space=14

NameError: name 'mymp' is not defined